# active profile
spring:
  profiles:
    active: "sdd-mysql-db"

---
# mem-h2-db
spring:
  config:
    activate:
      on-profile: mem-h2-db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todolist;mode=MYSQL;
    username: sa
    password:
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:sql/ddl-h2.sql
      data-locations: classpath:test/*.sql
  h2:
    console:
      enabled: true

---
# sdd-mysql-db
spring:
  config:
    activate:
      on-profile: sdd-mysql-db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todolist
    username: root
    password:
  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: classpath:sql/ddl-h2.sql

---
# deploy-mysql-db
spring:
  config:
    activate:
      on-profile: deploy-mysql-db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${TODO_URL}
    username: ${TODO_USER}
    password: ${TODO_PW}
