# active profile
spring:
  profiles:
    active: local-h2

---
# profile group
spring:
  profiles:
    group:
      local-h2: "local-mem-h2, local-log"
      local-mysql: "local-sdd-mysql, local-log"
      deploy-mysql: "deploy-aws-mysql, deploy-log"

---
# local-mem-h2
spring:
  config:
    activate:
      on-profile: local-mem-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todolist;mode=MYSQL;
    username: sa
    password:
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:sql/ddl-h2.sql
  h2:
    console:
      enabled: true

---
# local-sdd-mysql
spring:
  config:
    activate:
      on-profile: local-sdd-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todolist
    username: root
    password:
  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: classpath:sql/ddl-h2.sql

---
# deploy-aws-mysql
spring:
  config:
    activate:
      on-profile: deploy-aws-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${TODO_URL}
    username: ${TODO_USER}
    password: ${TODO_PW}
logging:
  file:
    path: ${FILE_PATH}

---
# log-group
spring:
  profiles:
    group:
      local-log: "console-log, low-level-log"
      deploy-log: "file-log, high-level-log"
