DROP TABLE IF EXISTS CARD;
CREATE TABLE CARD (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    CONTENTS VARCHAR(500),
    WRITER VARCHAR(20) NOT NULL,
    CARD_STATUS ENUM('TODO', 'PROGRESS', 'DONE'),
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
