DROP TABLE IF EXISTS CARD, LOG;
CREATE TABLE CARD (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CARD_INDEX INT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    CONTENTS VARCHAR(500),
    WRITER VARCHAR(20) NOT NULL,
    CARD_STATUS ENUM('TODO', 'PROGRESS', 'DONE'),
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOG
(
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    title               varchar(50) NOT NULL,
    current_status      ENUM('TODO', 'PROGRESS', 'DONE'),
    prev_status         ENUM('TODO', 'PROGRESS', 'DONE') default NULL,
    action_status       ENUM('ADD', 'REMOVE', 'UPDATE', 'MOVE'),
    action_time        DATETIME DEFAULT CURRENT_TIMESTAMP
);

