version: "3"

services:
  database:
    image: mysql:latest
    restart: always
    container_name: mysql-todolist
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=todo_list
      - MYSQL_ROOT_PASSWORD=todo_list
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
