spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/todo
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  sql:
    init:
      data-locations: classpath:sql/schema.sql
      mode: always
