DROP TABLE IF EXISTS history;
CREATE TABLE history
(
    id                 BIGINT generated by default as identity,
    card_action        VARCHAR(20),
    user_id            VARCHAR(20),
    card_title         VARCHAR(50),
    card_title_before  VARCHAR(50),
    card_status        VARCHAR(20),
    card_status_before VARCHAR(20),
    created_at         TIMESTAMP,
    primary key (id)

);


