DROP TABLE IF EXISTS card;

CREATE TABLE card
(
    id          BIGINT PRIMARY KEY NOT NULL,
    title       varchar(50)        NOT NULL,
    contents    varchar(500)       NOT NULL,
    user_id      varchar(20)        NOT NULL,
    card_status varchar(10)               NOT NULL,
    isDeleted   BOOLEAN            NOT NULL,
    created_at   TIMESTAMP          NOT NULL
);

DROP TABLE IF EXISTS history;
CREATE TABLE history
(
    id                 BIGINT generated by default as identity,
    card_action        VARCHAR(20),
    user_id            VARCHAR(20),
    card_title         VARCHAR(50),
    card_title_before  VARCHAR(50),
    card_status        VARCHAR(20),
    card_status_before VARCHAR(20),
    created_at         TIMESTAMP,
    primary key (id)

);
